### ISSUE TITLE
blank code cells added after reopening a notebook

### ISSUE THREAD

**Issue by yanghva** [AnWeber/httpbook#36] opened 2021-11-25 01:48 UTC
A lot of blank code cells were inserted after I reopen the notebook.
![image](https://user-images.githubusercontent.com/86941588/143355174-a4f85ba0-a28c-487a-80b1-f9498aec42f6.png)
I've turned 'Save With Region Delimiter' off, it didn't make a difference though
![image](https://user-images.githubusercontent.com/86941588/143356325-40056baa-6516-49e1-955f-20ae9f07ae8f.png)

**Comment by AnWeber** [comment] 2021-11-25 06:43
I would never have that issue before. Does the issue always occur? Do you have a code example.

**Comment by AnWeber** [comment] 2021-11-25 22:03
The setting `httpbook.saveWithRegionDelimiter` only change if always region delimiter are used or only if needed. If it is a RequestLine with Http Method and no script or variable is present, you can omit the ###, e.g.
```
GET https://httpbin.org/anything

GET https://httpbin.org/anything
```

I still have no idea how the behavior can occur. Each cell is currently an httpRegion/request for me. It would be interesting to know if the file also has the `###` persisted (error occurs on save) or not (error occurs on load).

**Comment by rngtng** [comment] 2021-11-28 22:15
fyi I experienced the same..

**Comment by AnWeber** [comment] 2021-11-28 22:24
Some hints how to reproduce issue. I do not use httpbook really often. First got hyped with Notebook UI, but now I prefer default editor. Did you edit file, before closing and reopening. Some special content. Anything special with files producing this error?

**Comment by rngtng** [comment] 2021-11-28 22:30
This allows you to reproduce:

```
GET https://example.com/

###
GET https://example.com/
```
Open this in httpbook, execute the first. Response will be added. Then save and you'll get extra `###`.

**Comment by AnWeber** [comment] 2021-11-30 05:58
The cause is a change in the behavior of the separator. Until recently, this was not considered to belong to a httpRegion/ request. However, since this can now contain the title and name of the httpRegion, it was included in the source.
I have now noticed that other recently made extensions (GRPC, MQTT) would cause errors because they are not taken into account.
https://github.com/AnWeber/httpbook/blob/main/src/extension/notebook/httpNotebookSerializer.ts#L142-L154

**Comment by AnWeber** [comment] 2021-11-30 21:26
I have fixed the cause of the empty cells. I am not quite happy with the as-is state, as unnecessary `###` lines now appear in the cell. However, these are needed when setting the name of the httpRegion/ request. I don't have the necessary time to do the correct fix right now though. I will make up for it after Christmas.

**Closed by AnWeber** 2021-11-30 21:26 UTC
