### ISSUE TITLE
Non-empty .http files sometimes open without a cell

### ISSUE THREAD

**Issue by dlucazeau** [AnWeber/httpbook#33] opened 2021-10-21 08:06 UTC
Hello,
If I open them normally, I see a single empty cell, whereas if I open them as a text file I see the non-empty content:
![2021-10-21_10-02-11](https://user-images.githubusercontent.com/4538922/138236519-f427360d-8223-4a53-a47a-205a42f1bacd.png)

Some .http files open correctly. It seems to me that they are always the same ones that open well or that open badly.
How to isolate the problem and correct it.

Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by AnWeber** [comment] 2021-10-21 11:07
I had already observed the error once myself. But closing the editor and opening it again was enough for me. However, I have not yet been able to reproduce it or determine the cause. 
I will install an additional logging to possibly find the cause. Unfortunately the NotebookSerializer interface does not use a filename and this complicates the search, but also the loading logic.

**Closed as completed** 2021-10-27 08:15 UTC
